# @package __global__

# Optimizer
batch_size: 16
epochs: 400
n_warm_up_step: 4000
grad_clip_thresh: 1.0
acc_steps: 1

betas: [0.9, 0.98]
eps: 1e-9
weight_decay: 0.0

aneal_steps: [100000, 200000, 300000]
aneal_rate: 0.3

# Save, log and synthesis
save_step: 20000
synth_step: 1000
log_step: 50
clear_Time: 20
restore_step: 0
